// %Pow Ratios Codes

% 1 - Delta/Theta
% 2 - Delta/Alpha
% 3 - Delta/Beta
% 4 - Delta/Gamma
% 5 - Theta/Delta
% 6 - Theta/Alpha
% 7 - Theta/Beta
% 8 - Theta/Gamma
% 9 - Alpha/Delta
% 10 - Alpha/Theta
% 11 - Alpha/Beta
% 12 - Alpha/Gamma
% 13 - Beta/Delta
% 14 - Beta/Theta
% 15 - Beta/Alpha
% 16 - Beta/Gamma
% 17 - Gamma/Delta
% 18 - Gamma/Theta
% 19 - Gamma/Alpha
% 20 - Gamma/Beta

PRC = {
'\delta/\theta', ...
'\delta/\alpha', ...
'\delta/\beta', ...
'\delta/\gamma', ...
'\theta/\delta', ...
'\theta/\alpha', ...
'\theta/\beta', ...
'\theta/\gamma', ...
'\alpha/\delta', ...
'\alpha/\theta', ...
'\alpha/\beta', ...
'\alpha/\gamma', ...
'\beta/\delta', ...
'\beta/\theta', ...
'\beta/\alpha', ...
'\beta/\gamma', ...
'\gamma/\delta', ...
'\gamma/\theta', ...
'\gamma/\alpha', ...
'\gamma/\beta'};

save('PRC.mat','PRC');