HOST =nvidia@10.46.36.149
TARGETDIR =~/Documents/Vision2019/

deploy: 
	scp LowerRange.txt $(HOST):$(TARGETDIR)
	scp UpperRange.txt $(HOST):$(TARGETDIR)
	scp ObjectDetection.py $(HOST):$(TARGETDIR)
	scp Main.py $(HOST):$(TARGETDIR)
	scp TargetUtils.py $(HOST):$(TARGETDIR)
	scp VisionTarget.png $(HOST):$(TARGETDIR)
